#define FILE_VERSION        1,6,11,16
#define STR_FILE_VERSION   "1,6,11,16\0"
#define STR_FILE_VERSION2  "1.6.11.16"
#define STR_DATE           "04/03/2012\0"
#define NOMFENETRE    "HxCFloppyEmulator "##STR_FILE_VERSION2

#define FILEVER        FILE_VERSION
#define PRODUCTVER     FILE_VERSION
#define STRFILEVER     STR_FILE_VERSION
#define STRPRODUCTVER  STR_FILE_VERSION
