.TH UCSIM 1
.SH NAME
uCsim \- Micro\-controller simulator
.SH SYNOPSIS
.B s51|sz80|savr|sxa
.RB \-t type
.SH DESCRIPTION
.I s51
command is used to simulate MCS51 controller family
.PP
.B Options of the command
.TP
.B \-t type
Specifies type of the controller.
.PP
.TP
.B \-s file
Serial file
.SH EXAMPLES
None yet.
.SH FILES
None.
.SH "SEE ALSO"
sdcc(1), sdcdb(1).
.SH DIAGNOSTICS
None.
.SH BUGS
Probably many.
.SH AUTHORS
xy
.RS 0
zc
.RE 0