//-----------------------------LICENSE NOTICE------------------------------------
//  This file is part of CPCtelera: An Amstrad CPC Game Engine
//  Copyright (C) 2015 ronaldo / Fremos / Cheesetea / ByteRealms (@FranGallegoBR)
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//------------------------------------------------------------------------------

#include <cpctelera.h>

// G_Sprite is automatically generated by makefile, converting sprite.bin file
// into G_sprite definition in sprite.c file. We declare G_sprite as extern
// for the compiler to know that this symbol exists
extern const u8 G_sprite[192];

// Use this palette with just 5 colours
const u8 g_palette[5] = { 
// HW Value  | FW Value | Colour name
//-------------------------------------
   0x14,  // |    0     | Black
   0x15,  // |    2     | Bright Blue
   0x13,  // |   20     | Bright Cyan
   0x16,  // |    9     | Green
   0x0E   // |   15     | Orange
};

////////////////////////////////////////////////////////////////////////
// MAIN: Just prints a sprite on top-left corner of the screen
//       The sprite comes from a binary file which is automatically converted
//
void main(void) {
   // Initializing the CPC
   cpct_disableFirmware();          // Disable firmware (as we are going to use mode and colours)
   cpct_setVideoMode(0);            // Set video mode 0 (160x200, 16 colours)
   cpct_setPalette(g_palette, 5);   // Set first 5 colours from our palette (we aren't going to use more)
   
   // Draw G_character sprite at top-left corner of the screen (first byte of video memory,
   // which is located at 0xC000 in memory by default). 
   cpct_drawSprite(G_sprite, CPCT_VMEM_START, 8, 24);
   
   // Loop forever
   while (1);
}
