#!/bin/sh
# Script to "cross" compile with mingw32 under Cygwin

./configure -C \
--prefix="/sdcc" \
--datarootdir="/sdcc" \
docdir="\${datarootdir}/doc" \
include_dir_suffix="include" \
non_free_include_dir_suffix="non-free/include" \
lib_dir_suffix="lib" \
non_free_lib_dir_suffix="non-free/lib" \
sdccconf_h_dir_separator="\\\\" \
CC="gcc -mno-cygwin" \
CXX="g++ -mno-cygwin"

make 2>&1 | tee make.log
