#define NOP instruction_00
#define OUTLB instruction_02
#define OUTDBB instruction_02
#define ADDI8 instruction_03
#define JMP0 instruction_04
#define ENI instruction_05
#define DECA instruction_07
#define INS instruction_08
#define INP0 instruction_08
#define IN1 instruction_09
#define IN2 instruction_0a
#define MOVDAP4 instruction_0c
#define MOVDAP5 instruction_0d
#define MOVDAP6 instruction_0e
#define MOVDAP7 instruction_0f
#define INCIR0 instruction_10
#define INCIR1 instruction_11
#define JB0 instruction_12
#define ADCI8 instruction_13
#define CALL0 instruction_14
#define DISI instruction_15
#define JTF instruction_16
#define INCA instruction_17
#define INCR0 instruction_18
#define INCR1 instruction_19
#define INCR2 instruction_1a
#define INCR3 instruction_1b
#define INCR4 instruction_1c
#define INCR5 instruction_1d
#define INCR6 instruction_1e
#define INCR7 instruction_1f
#define XCHIR0 instruction_20
#define XCHIR1 instruction_21
#define INDBB instruction_22
#define MOVAI8 instruction_23
#define JMP1 instruction_24
#define ENTCNTI instruction_25
#define JNT0 instruction_26
#define CLRA instruction_27
#define XCHR0 instruction_28
#define XCHR1 instruction_29
#define XCHR2 instruction_2a
#define XCHR3 instruction_2b
#define XCHR4 instruction_2c
#define XCHR5 instruction_2d
#define XCHR6 instruction_2e
#define XCHR7 instruction_2f
#define XCHDIR0 instruction_30
#define XCHDIR1 instruction_31
#define JB1 instruction_32
#define CALL1 instruction_34
#define DISTCNTI instruction_35
#define JT0 instruction_36
#define CPLA instruction_37
#define MOVDP4A instruction_3c
#define MOVDP5A instruction_3d
#define MOVDP6A instruction_3e
#define MOVDP7A instruction_3f
#define ORLIR0 instruction_40
#define ORLIR1 instruction_41
#define MOVAT instruction_42
#define ORLI8 instruction_43
#define JMP2 instruction_44
#define STRTCNT instruction_45
#define JNT1 instruction_46
#define SWAPA instruction_47
#define ORLR0 instruction_48
#define ORLR1 instruction_49
#define ORLR2 instruction_4a
#define ORLR3 instruction_4b
#define ORLR4 instruction_4c
#define ORLR5 instruction_4d
#define ORLR6 instruction_4e
#define ORLR7 instruction_4f
#define ANLIR0 instruction_50
#define ANLIR1 instruction_51
#define JB2 instruction_52
#define ANLI8 instruction_53
#define CALL2 instruction_54
#define STRTT instruction_55
#define JT1 instruction_56
#define DAA instruction_57
#define ANLR0 instruction_58
#define ANLR1 instruction_59
#define ANLR2 instruction_5a
#define ANLR3 instruction_5b
#define ANLR4 instruction_5c
#define ANLR5 instruction_5d
#define ANLR6 instruction_5e
#define ANLR7 instruction_5f
#define ADDIR0 instruction_60
#define ADDIR1 instruction_61
#define MOVTA instruction_62
#define JMP3 instruction_64
#define STOPTCNT instruction_65
#define RRC instruction_67
#define ADDR0 instruction_68
#define ADDR1 instruction_69
#define ADDR2 instruction_6a
#define ADDR3 instruction_6b
#define ADDR4 instruction_6c
#define ADDR5 instruction_6d
#define ADDR6 instruction_6e
#define ADDR7 instruction_6f
#define ADCIR0 instruction_70
#define ADCIR1 instruction_71
#define JB3 instruction_72
#define CALL3 instruction_74
#define JF1 instruction_76
#define RR instruction_77
#define ADCR0 instruction_78
#define ADCR1 instruction_79
#define ADCR2 instruction_7a
#define ADCR3 instruction_7b
#define ADCR4 instruction_7c
#define ADCR5 instruction_7d
#define ADCR6 instruction_7e
#define ADCR7 instruction_7f
#define MOVXAIR0 instruction_80
#define MOVXAIR1 instruction_81
#define RET instruction_83
#define JMP4 instruction_84
#define CLRF0 instruction_85
#define ORLDP4A instruction_8c
#define ORLDP5A instruction_8d
#define ORLDP6A instruction_8e
#define ORLDP7A instruction_8f
#define MOVXIR0A instruction_90
#define MOVXIR1A instruction_91
#define JB4 instruction_92
#define RETR instruction_93
#define CALL4 instruction_94
#define CPLF0 instruction_95
#define JNZ instruction_96
#define CLRC instruction_97
#define ANLDP4A instruction_9c
#define ANLDP5A instruction_9d
#define ANLDP6A instruction_9e
#define ANLDP7A instruction_9f
#define MOVIR0A instruction_a0
#define MOVIR1A instruction_a1
#define MOVPAIA instruction_a3
#define JMP5 instruction_a4
#define CLRF1 instruction_a5
#define CPLC instruction_a7
#define MOVR0A instruction_a8
#define MOVR1A instruction_a9
#define MOVR2A instruction_aa
#define MOVR3A instruction_ab
#define MOVR4A instruction_ac
#define MOVR5A instruction_ad
#define MOVR6A instruction_ae
#define MOVR7A instruction_af
#define MOVIR0I8 instruction_b0
#define MOVIR1I8 instruction_b1
#define JB5 instruction_b2
#define JMPPIA instruction_b3
#define CALL5 instruction_b4
#define CPLF1 instruction_b5
#define JF0 instruction_b6
#define MOVR0I8 instruction_b8
#define MOVR1I8 instruction_b9
#define MOVR2I8 instruction_ba
#define MOVR3I8 instruction_bb
#define MOVR4I8 instruction_bc
#define MOVR5I8 instruction_bd
#define MOVR6I8 instruction_be
#define MOVR7I8 instruction_bf
#define JMP6 instruction_c4
#define SELRB0 instruction_c5
#define JZ instruction_c6
#define MOVAF instruction_c7
#define DECR0 instruction_c8
#define DECR1 instruction_c9
#define DECR2 instruction_ca
#define DECR3 instruction_cb
#define DECR4 instruction_cc
#define DECR5 instruction_cd
#define DECR6 instruction_ce
#define DECR7 instruction_cf
#define XRLIR0 instruction_d0
#define XRLIR1 instruction_d1
#define JB6 instruction_d2
#define XRLI8 instruction_d3
#define CALL6 instruction_d4
#define SELRB1 instruction_d5
#define MOVFA instruction_d7
#define XRLR0 instruction_d8
#define XRLR1 instruction_d9
#define XRLR2 instruction_da
#define XRLR3 instruction_db
#define XRLR4 instruction_dc
#define XRLR5 instruction_dd
#define XRLR6 instruction_de
#define XRLR7 instruction_df
#define MOVP3AIA instruction_e3
#define JMP7 instruction_e4
#define SELMB0 instruction_e5
#define JNC instruction_e6
#define RL instruction_e7
#define DJNZR0 instruction_e8
#define DJNZR1 instruction_e9
#define DJNZR2 instruction_ea
#define DJNZR3 instruction_eb
#define DJNZR4 instruction_ec
#define DJNZR5 instruction_ed
#define DJNZR6 instruction_ee
#define DJNZR7 instruction_ef
#define MOVAIR0 instruction_f0
#define MOVAIR1 instruction_f1
#define JB7 instruction_f2
#define CALL7 instruction_f4
#define SELMB1 instruction_f5
#define JC instruction_f6
#define RLC instruction_f7
#define MOVAR0 instruction_f8
#define MOVAR1 instruction_f9
#define MOVAR2 instruction_fa
#define MOVAR3 instruction_fb
#define MOVAR4 instruction_fc
#define MOVAR5 instruction_fd
#define MOVAR6 instruction_fe
#define MOVAR7 instruction_ff
