#!/bin/sh

TARGET=linux

if [ "$#" -ge 1 ]; then
    case "$1" in
	[lL]*) TARGET=linux;shift;;
	[mM]*) TARGET=mingw;shift;;
	*) echo "Unknown target \"${1}\"" >&2; exit 1;;
    esac
fi

if [ -f devel ]; then
	export CXXFLAGS=""
fi

case $TARGET in
    linux)
	./configure --prefix=${HOME}/local \
	--enable-ucsim \
	--enable-dlso \
	--enable-serio \
	--enable-z80 \
	--enable-xa \
	"$@"
	;;
    mingw)
	export CC=/usr/local/cross-tools/mingw32/bin/gcc
	export CXX=/usr/local/cross-tools/mingw32/bin/g++
	./configure --prefix=${HOME}/local \
	--disable-ucsim \
	--disable-dlso \
	--disable-serio \
	--enable-z80 \
	--enable-xa \
	"$@"
	;;
    *)
	echo >&2 "Do not know how to configure!"
	;;
esac

# End of conf
